seed: 3407
task: 'expr'


train_data:
  name: 'SequenceData'
  args:
    feat_root: '/data1/ABAW/ABAW5/Aff-Wild2/feat/'
    label_root: '/data1/ABAW/ABAW5/Aff-Wild2/annotations/EXPR_Classification_Challenge/Train_Set'
    seq_len: 128
    task: 'expr'
    pad_mode: 'repeat_last'
    feat_dict:
      fau: 512
      ires100_7_expr: 512
      ecapatdnn: 512
      mae_emotionet: 768
    mask_aug: true
    mask_ratio: 0.05
    label_smooth: false
    smooth_factor: 0.0

val_data:
  name: 'SequenceData'
  args:
    feat_root: '/data1/ABAW/ABAW5/Aff-Wild2/feat/'
    label_root: '/data1/ABAW/ABAW5/Aff-Wild2/annotations/EXPR_Classification_Challenge/Validation_Set'
    seq_len: 128
    task: 'expr'
    pad_mode: 'repeat_last'
    feat_dict:
      fau: 512
      ires100_7_expr: 512
      ecapatdnn: 512
      mae_emotionet: 768

dataloader:
  batch_size: 32
  num_workers: 32
  pin_memory: true
  collate_fn: 'base_collate_fn'

model:
  name: 'BERT'
  args:
    input_dim: 2304
    feedforward_dim: 1024
    affine_dim: 1024
    nheads: 4
    nlayers: 4
    dropout: 0.3
    use_pe: True
    seq_len: 128
    head_dropout: 0.1
    head_dims:
      - 512
      - 256
    out_dim: 8
    task: 'expr'

solver:
  name: 'RDropSolver'
  args:
    epoch: 50

  optimizer:
    name: 'Adam'
    args:
      lr: !!float 1e-4
      weight_decay: !!float 1e-5

  lr_scheduler:
    name: 'StepLR'
    args:
      step_size: 20
      gamma: 0.1

  loss:
    name: 'RDropLoss'
    args:
      weight: [1.0, 10.50702, 16.41711, 19.78342, 1.85224, 2.23410, 5.62630, 1.06086]
      alpha: 5

  logger:
    log_root: '/data1/mly/projects/abaw5/log/'
    suffix: 'expr_tdnn_mask1'

  metric:
    name: 'ExprMetric'
